---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconnect
  labels:
    app: devconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devconnect
  template:
    metadata:
      labels:
        app: devconnect
    spec:
      containers:
      - name: devconnect-container
        image: 286395681879.dkr.ecr.us-east-1.amazonaws.com/devconnect:latest
        ports:
        - containerPort: 3000
...
