---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevConnect-app
  labels:
    app: DevConnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DevConnect-app
  template:
    metadata:
      labels:
        app: DevConnect-app
    spec:
      containers:
      - name: DevConnect-container
        image: https://286395681879.dkr.ecr.us-east-1.amazonaws.com/devconnect:latest
        ports:
        - containerPort: 3000
...
