# Deployment for PandaCloud App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconnect-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: devconnect-app
  template:
    metadata:
      labels:
        app: devconnect-app
    spec:
      containers:
        - name: devconnect-container
          image: 286395681879.dkr.ecr.us-east-1.amazonaws.com/devconnect:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
# Service to expose the devconnnect App
apiVersion: v1
kind: Service
metadata:
  name: devconnect-service
spec:
  selector:
    app: devconnect-app
  type: LoadBalancer
  ports:
    - name: http
      port: 5000         # Expose on port 5000 externally
      targetPort: 5000   # Container listens on 5000
