---
apiVersion: v1
kind: Service
metadata:
  name: devconnect
  labels:
    app: devconnect
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: devconnect
  type: LoadBalancer
...
